version: '3'

services:
  postgres:
    image: 'postgres:10'
    container_name: 'postgres'
    expose:
      - 5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER : admin
      POSTGRES_PASSWORD : admin
      POSTGRES_DB : users
  app:
    build: ./
    container_name: 'demo-person'
    ports:
      - '8080:8080'

volumes:
  data: {}